services:
  - docker

before_install:
  - docker build -t mnrowe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mnrowe/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket: "elasticbeanstalk-us-east-1-020537610738"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

